
theme: minima


title: "Portfolio ของ Boriwat Wongtama"
description: "ยินดีต้อนรับสู่ Portfolio ของ Boriwat Wongtama แสดงผลงานและประสบการณ์ในด้านการพัฒนาเว็บและงานดิจิทัล"
author: 
  name: "Boriwat Wongtama"
  email: "66025740@up.ac.th"  


markdown: kramdown
permalink: pretty


social_links:
  - name: GitHub
    url: "https://github.com/boriwat-wtm"
  - name: LinkedIn
    url: "https://linkedin.com/in/boriwatwongtama"

# การตั้งค่าเมนูในหน้าเว็บ (ถ้ามี)
navbar:
  - text: "เกี่ยวกับฉัน"
    url: "/about"
  - text: "ผลงาน"
    url: "/projects"
  - text: "ติดต่อ"
    url: "/contact"
